import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, BarChart3, Check, CircleHelp, IndianRupee, Link2, Plus, RotateCcw, ShieldCheck, Sparkles, Trash2, Wallet, X } from 'lucide-react';
import './styles.css';

type Expense = { id: string; name: string; amount: number; category: string; date?: string };
type CheckRecord = { id: string; name: string; price: number; result: string; createdAt: string };
type Budget = { month: string; income: number; savings: number; recurring: Expense[]; oneOff: Expense[]; checks: CheckRecord[] };
const key = 'monthly-budget-checker-v1';
const money = (n: number) => `₹${Math.max(0, n).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`;
const monthNow = () => new Date().toISOString().slice(0, 7);
const blank = (): Budget => ({ month: monthNow(), income: 30000, savings: 500, recurring: [], oneOff: [], checks: [] });
const load = (): Budget => { try { return JSON.parse(localStorage.getItem(key) || '') || blank(); } catch { return blank(); } };
const uid = () => Math.random().toString(36).slice(2, 10);

function App() {
  const [budget, setBudget] = useState<Budget>(load);
  const [tab, setTab] = useState<'overview'|'expenses'|'checker'>('overview');
  const [expenseType, setExpenseType] = useState<'recurring'|'oneOff'>('oneOff');
  const [form, setForm] = useState({ name: '', amount: '', category: 'Essentials', date: new Date().toISOString().slice(0, 10) });
  const [product, setProduct] = useState({ name: '', url: '', price: '' });
  const [notice, setNotice] = useState('');
  useEffect(() => localStorage.setItem(key, JSON.stringify(budget)), [budget]);
  const recurringTotal = useMemo(() => budget.recurring.reduce((s, e) => s + e.amount, 0), [budget.recurring]);
  const spent = useMemo(() => budget.oneOff.reduce((s, e) => s + e.amount, 0), [budget.oneOff]);
  const safe = budget.income - recurringTotal - spent - budget.savings;
  const fixedAndReserve = recurringTotal + budget.savings;
  const progress = budget.income ? Math.min(100, Math.round((fixedAndReserve + spent) / budget.income * 100)) : 0;
  const setNumber = (field: 'income'|'savings', value: string) => setBudget(b => ({ ...b, [field]: Math.max(0, Number(value) || 0) }));
  const addExpense = (e: React.FormEvent) => { e.preventDefault(); const amount = Number(form.amount); if (!form.name.trim() || amount <= 0) { setNotice('Add a name and a positive amount.'); return; } const item: Expense = { id: uid(), name: form.name.trim(), amount, category: form.category, ...(expenseType === 'oneOff' ? { date: form.date } : {}) }; setBudget(b => ({ ...b, [expenseType === 'oneOff' ? 'oneOff' : 'recurring']: [...b[expenseType === 'oneOff' ? 'oneOff' : 'recurring'], item] })); setForm(f => ({ ...f, name: '', amount: '' })); setNotice('Expense added.'); };
  const removeExpense = (id: string, type: 'recurring'|'oneOff') => setBudget(b => ({ ...b, [type]: b[type].filter(e => e.id !== id) }));
  const analyze = (e: React.FormEvent) => { e.preventDefault(); const price = Number(product.price); if (price <= 0) { setNotice('Enter a product price to check affordability.'); return; } const after = safe - price; const affordable = price <= Math.max(0, safe); const careful = affordable && after < Math.max(1000, budget.income * .1); const result = affordable ? (careful ? 'Buy carefully' : 'Buy now') : 'Wait and save'; const record: CheckRecord = { id: uid(), name: product.name || 'Product', price, result, createdAt: new Date().toISOString() }; setBudget(b => ({ ...b, checks: [record, ...b.checks].slice(0, 10) })); setNotice('Affordability check updated.'); };
  const resetMonth = () => { if (confirm('Start a new month? Your current month will be kept in history only through its saved checks.')) setBudget(b => ({ ...b, month: monthNow(), oneOff: [], checks: [] })); };
  const daysToSave = (price: number) => { const monthlySurplus = Math.max(0, budget.income - recurringTotal - budget.savings); if (!monthlySurplus) return 'There is no monthly surplus available for saving yet.'; const months = price / monthlySurplus; return months <= 1 ? `About ${Math.ceil(months * 30)} days at your current surplus.` : `About ${Math.ceil(months)} months at your current surplus.`; };
  const analyzedPrice = Number(product.price) || 0; const after = safe - analyzedPrice; const isAffordable = analyzedPrice > 0 && analyzedPrice <= Math.max(0, safe); const isCareful = isAffordable && after < Math.max(1000, budget.income * .1);
  return <div className="app"><header><div className="brand"><div className="brand-mark"><Wallet size={21}/></div><div><strong>paisa<span>wise</span></strong><small>Spend with intention</small></div></div><button className="month-button" onClick={resetMonth}><RotateCcw size={16}/> New month</button></header>
    <main><section className="hero"><div><p className="eyebrow">{new Date(`${budget.month}-01`).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</p><h1>Your money, <em>made clear.</em></h1><p className="subhead">Know what you can spend today, and what your future self will thank you for.</p></div><div className="hero-tip"><Sparkles size={17}/><span>Every ₹ saved is a choice<br/><b>you make for yourself.</b></span></div></section>
      <nav><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='expenses'?'active':''} onClick={()=>setTab('expenses')}>Expenses</button><button className={tab==='checker'?'active':''} onClick={()=>setTab('checker')}>Can I afford it?</button></nav>
      {notice && <div className="notice"><Check size={16}/>{notice}<button onClick={()=>setNotice('')}><X size={15}/></button></div>}
      {tab === 'overview' && <><section className="metrics"><div className="metric dark"><span>Safe to spend</span><strong>{money(safe)}</strong><small>after expenses & savings</small><div className="metric-icon"><Wallet size={19}/></div></div><div className="metric"><span>Monthly income</span><strong>{money(budget.income)}</strong><small>your total take-home</small><IndianRupee className="metric-icon" size={19}/></div><div className="metric"><span>Monthly savings</span><strong>{money(budget.savings)}</strong><small>protected, always</small><ShieldCheck className="metric-icon" size={19}/></div></section><section className="grid-two"><div className="card balance"><div className="card-title"><div><p className="eyebrow">This month</p><h2>Your spending snapshot</h2></div><BarChart3 size={20}/></div><div className="bar"><i style={{width:`${progress}%`}}/></div><div className="bar-labels"><span><b>{money(spent)}</b> spent</span><span><b>{money(Math.max(0, safe))}</b> safe to spend</span></div><div className="snapshot"><div><span>Recurring expenses</span><b>{money(recurringTotal)}</b></div><div><span>One-off expenses</span><b>{money(spent)}</b></div><div><span>Protected savings</span><b className="green">{money(budget.savings)}</b></div></div></div><div className="card quick"><div className="card-title"><div><p className="eyebrow">Quick check</p><h2>Thinking of buying something?</h2></div><CircleHelp size={20}/></div><p>Check a product before you commit. We’ll show you exactly what stays in your pocket.</p><button className="primary full" onClick={()=>setTab('checker')}>Check affordability <ArrowRight size={17}/></button></div></section></>}
      {tab === 'expenses' && <section className="grid-two expense-layout"><div className="card"><div className="card-title"><div><p className="eyebrow">Build your month</p><h2>Budget basics</h2></div></div><label>Monthly income<input type="number" value={budget.income} onChange={e=>setNumber('income',e.target.value)} min="0"/></label><label>Minimum savings reserve<input type="number" value={budget.savings} onChange={e=>setNumber('savings',e.target.value)} min="0"/></label><p className="helper">This amount is protected and never counted as spendable.</p><hr/><div className="segmented"><button className={expenseType==='oneOff'?'selected':''} onClick={()=>setExpenseType('oneOff')}>One-off expense</button><button className={expenseType==='recurring'?'selected':''} onClick={()=>setExpenseType('recurring')}>Recurring expense</button></div><form onSubmit={addExpense}><label>Name<input placeholder="e.g. Groceries" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="form-row"><label>Amount<input type="number" min="1" placeholder="₹ 0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Essentials</option><option>Transport</option><option>Health</option><option>Fun</option><option>Other</option></select></label></div>{expenseType==='oneOff'&&<label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label>}<button className="primary full" type="submit"><Plus size={17}/> Add expense</button></form></div><div className="card expense-list"><div className="card-title"><div><p className="eyebrow">Your entries</p><h2>Where it goes</h2></div><span className="count">{budget.recurring.length + budget.oneOff.length}</span></div>{[...budget.recurring.map(e=>({...e, type:'recurring' as const})), ...budget.oneOff.map(e=>({...e,type:'oneOff' as const}))].length===0?<div className="empty">No expenses yet.<br/>Add your first one to make your balance real.</div>:[...budget.recurring.map(e=>({...e,type:'recurring' as const})), ...budget.oneOff.map(e=>({...e,type:'oneOff' as const}))].map(e=><div className="expense-row" key={e.id}><div className="expense-dot">{e.category[0]}</div><div><b>{e.name}</b><small>{e.category} · {e.type==='recurring'?'Every month':e.date}</small></div><strong>{money(e.amount)}</strong><button onClick={()=>removeExpense(e.id,e.type)} aria-label="Delete"><Trash2 size={15}/></button></div>)}</div></section>}
      {tab === 'checker' && <section className="checker"><div className="card checker-form"><div className="card-title"><div><p className="eyebrow">Before you buy</p><h2>Can I afford it?</h2></div><Link2 size={20}/></div><p className="muted">Paste a product link or enter the price manually. We’ll do the honest math.</p><form onSubmit={analyze}><label>Product name<input placeholder="e.g. Noise-cancelling headphones" value={product.name} onChange={e=>setProduct({...product,name:e.target.value})}/></label><label>Product link <span className="optional">optional</span><input type="url" placeholder="https://…" value={product.url} onChange={e=>setProduct({...product,url:e.target.value})}/></label><label>Price in INR<input type="number" min="1" placeholder="₹ 0" value={product.price} onChange={e=>setProduct({...product,price:e.target.value})}/></label><p className="helper"><CircleHelp size={14}/> Automatic price detection can be connected through <code>POST /api/product-price</code>. For now, confirm the price manually.</p><button className="primary full" type="submit">Check my affordability <ArrowRight size={17}/></button></form></div><div className={`card result ${analyzedPrice?'has-result':''}`}>{!analyzedPrice?<div className="result-empty"><div className="result-icon"><Sparkles size={24}/></div><h2>Your answer will appear here</h2><p>Enter a price to see your affordability score, what remains after buying, and whether it’s a good time.</p></div>:<><div className="result-label"><span className={isAffordable?'pill green-pill':'pill orange-pill'}>{isAffordable?(isCareful?'Buy carefully':'Affordable'):'Wait and save'}</span><span className="score">{Math.max(0, Math.min(100, Math.round((safe / analyzedPrice) * 50)))} / 100 score</span></div><h2>{isAffordable?(isCareful?'You can afford it, carefully.':'Yes, you can afford this.'):'Not this month — and that’s okay.'}</h2><p className="result-copy">{isAffordable?`After buying ${product.name||'this product'}, you’ll have ${money(after)} left to spend. Your ${money(budget.savings)} savings reserve stays protected.`:`This purchase is ${money(Math.max(0, analyzedPrice-safe))} above your safe-to-spend amount. Waiting keeps your ${money(budget.savings)} savings reserve protected.`}</p><div className="result-stats"><div><span>After purchase</span><b>{money(after)}</b></div><div><span>Monthly reserve</span><b className="green">{money(budget.savings)}</b></div></div>{!isAffordable&&<div className="save-callout"><strong>Saving plan</strong><span>{daysToSave(analyzedPrice)}</span></div>}<div className="recommendation"><Sparkles size={16}/><span><b>{isAffordable?(isCareful?'Our take: wait if this is a want.':'Our take: it fits your plan.'):'Our take: give it some time.'}</b><br/>{isAffordable?'Make sure this purchase is worth the trade-off.':'A little patience now protects the things you said matter most.'}</span></div></>}</div></section>}
      {budget.checks.length>0 && tab !== 'checker' && <section className="card history"><div className="card-title"><div><p className="eyebrow">Recent checks</p><h2>Purchase decisions</h2></div></div>{budget.checks.map(c=><div className="history-row" key={c.id}><span>{c.name}</span><span>{money(c.price)}</span><b className={c.result==='Wait and save'?'orange':''}>{c.result}</b></div>)}</section>}
    </main><footer><span>paisa<span>wise</span> · Your money, your choices.</span><span>Stored privately on this device</span></footer></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
